version: "3"
services:
  nextjs:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env.local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresql
volumes:
  db-data:
